ruby "2.5.3"

source "https://rubygems.org"

gem "active_model_serializers", ">= 0.10.10"
gem "audited", ">= 4.9.0"
gem "redis-rack-cache", "2.0.2"
gem "json", "2.3.0"

group :development, :test do
  gem "faker"
end

group :test do
  gem "webmock", ">= 3.6.0"
end

group :development do
  gem "spring", ">= 2.1.0"
end
