ruby "2.5.3"

source "https://rubygems.org"

gem "active_model_serializers"
gem "audited", ">= 5.3.3"
gem "redis-rack-cache", "1.1"
gem "json", "1.0.0"

group :development, :test do
  gem "faker"
end

group :test do
  gem "webmock"
end

group :development do
  gem "spring"
end
