ruby "2.5.3"

source "https://rubygems.org"

gem "active_model_serializers", ">= 0.10.9"
gem "audited"
gem "redis-rack-cache", "2.0.2"
gem "json", "1.5.5"

group :development, :test do
  gem "faker"
end

group :test do
  gem "webmock"
end

group :development do
  gem "spring"
end
